version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - misspell
    - ineffassign
    - unconvert
    - ginkgolinter

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
