---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - keleustes.skaphos.io
  resources:
  - applications
  - approvals
  - cells
  - deployments
  - deploymenttargets
  - environments
  - freezewindows
  - healthchecks
  - notifiers
  - promotionpolicies
  - promotions
  - releases
  - sources
  - syncplans
  - syncruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keleustes.skaphos.io
  resources:
  - applications/finalizers
  - approvals/finalizers
  - cells/finalizers
  - deployments/finalizers
  - deploymenttargets/finalizers
  - environments/finalizers
  - freezewindows/finalizers
  - healthchecks/finalizers
  - notifiers/finalizers
  - promotionpolicies/finalizers
  - promotions/finalizers
  - releases/finalizers
  - sources/finalizers
  - syncplans/finalizers
  - syncruns/finalizers
  verbs:
  - update
- apiGroups:
  - keleustes.skaphos.io
  resources:
  - applications/status
  - approvals/status
  - cells/status
  - deployments/status
  - deploymenttargets/status
  - environments/status
  - freezewindows/status
  - healthchecks/status
  - notifiers/status
  - promotionpolicies/status
  - promotions/status
  - releases/status
  - sources/status
  - syncplans/status
  - syncruns/status
  verbs:
  - get
  - patch
  - update
