apiVersion: keleustes.skaphos.io/v1alpha1
kind: Cell
metadata:
  name: guest-prod
spec:
  environment: prod
  purpose: guest-facing
  failureBoundary: guest
  regions:
    - westus2
    - westcentralus
