#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Skaphos
# SPDX-License-Identifier: MIT
#
# Regenerate THIRD_PARTY_LICENSES.md from the current Go module graph.
# Invoked by `go -C tools tool task licenses`. Re-run after every go.mod
# change that adds or upgrades modules, and commit the resulting file.
#
# Scope: every Go package reachable from ./cmd/manager and
# ./cmd/keleustesctl (the two shipped binaries). The agent target
# enters the build list when ./cmd/agent lands.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

TARGETS=(./cmd/manager ./cmd/keleustesctl)

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# go-licenses report emits CSV: <package>,<license-url>,<spdx-id>.
# Sort for stable diff output.
go run github.com/google/go-licenses@v1.6.0 report "${TARGETS[@]}" 2>/dev/null \
  | sort > "$TMP"

{
  cat <<'EOF'
<!--
SPDX-FileCopyrightText: 2026 Skaphos
SPDX-License-Identifier: MIT
-->

# Third-Party Licenses

This file is generated by `go -C tools tool task licenses` from the
current Go module graph (every Go package reachable from
`./cmd/manager` and `./cmd/keleustesctl`). Do not edit by hand —
re-run the task after every `go.mod` change and commit the result.

The repo-root `NOTICE` file carries Keleustes' own copyright statement
and a pointer back here. When adopting a new Apache-2.0 dependency that
ships its own `NOTICE`, append the upstream NOTICE content there per
Apache-2.0 §4(d). See `docs/licenses.md` for the full contract.

| Module | License | Source |
|--------|---------|--------|
EOF
  awk -F',' '{printf "| `%s` | %s | [link](%s) |\n", $1, $3, $2}' "$TMP"
} > THIRD_PARTY_LICENSES.md

echo "Wrote $(wc -l < THIRD_PARTY_LICENSES.md) lines to THIRD_PARTY_LICENSES.md"
